import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="flex justify-center">
          <div className="flex space-x-6 mb-3">
                <a href="https://github.com/mzsellem-GA">
                    <img
                      src="/github-mark.png"
                      alt="github logo"
                      width="50"
                      height="50"
                    />
                </a>
                <a
                    href="https://www.linkedin.com/in/marley-sellem/"
                    className="mt-2"
                >
                    <img
                      src="/li-logo.png"
                      alt="linkedin logo"
                      width="50"
                      height="50"
                    />
                </a>
          </div>
        </footer>
      </body>
    </html>
  )
}
